openapi: 3.0.0
info:
  title: Latest Bookings
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: insights
  - name: insights > latestbookings
paths:
  /insights/latestbookings/:
    get:
      tags:
        - insights > latestbookings
      summary: Get the latest hotel and air booking for a particular user.
      description: Get the latest hotel and air booking for a particular user.
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                Airlines:
                  BookingClass: <string>
                  Code: <string>
                Hotel:
                  Location: <string>
                  StarRating: <integer>
