openapi: 3.0.0
info:
  title: Localized Data
  description: >-
    Invoice includes various status codes, and error messages. This API provides
    a method to list the localized strings of various codes.
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
tags:
  - name: invoice
  - name: invoice > localizeddata
paths:
  /invoice/localizeddata:
    get:
      tags:
        - invoice > localizeddata
      summary: 'Get localized string of various codes in Invoice. '
      description: 'Returns the  localized string of various codes in Invoice. '
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: type
          in: query
          schema:
            type: string
          description: >-
            Valid types are -    approvalStatus, paymentStatus, expenseType,
            ledgerCode, dataSourceCode, payMethod, receiptConfirmation,
            unitOfMeasure.
          example: <string>
        - name: langCode
          in: query
          schema:
            type: string
          description: >-
            Optional. The language code requested. lang codes examples - de, en,
            es, fr, fr_CA, hu, it, ja, pl, pt_BR
          example: <string>
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                LocalizationData:
                  Code: <string>
                  LangCode: <string>
                  LocalizedValue: <string>
                TotalCount: <integer>
