openapi: 3.0.0
info:
  title: Receipt Images
  description: >-
    Allows for the management of receipt images attached to expense reports,
    expense entries, and payment requests. You can retrieve existing images by
    Image ID, and upload new images to a User. This API allows you to upload
    images in a predefined format and size targeting a specific resource or user
    in SAP Concur. You can also pull images down from SAP Concur by either
    displaying them in the browser or downloading the image content to save
    locally. Note: This API is not designed to obtain the receipt images
    attached to an expense report. If you are an Enterprise Partner creating
    integrations that are intended to obtain final-approved Expense or Invoice
    data, and the accompanying receipt images that substantiate those
    transactions you will need to use Image v1.
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    oauth2Auth:
      type: http
      scheme: oauth2
security:
  - oauth2Auth: []
tags:
  - name: expense
  - name: expense > receiptimages
  - name: expense > receiptimages > {id}
paths:
  /expense/receiptimages/{id}:
    get:
      tags:
        - expense > receiptimages > {id}
      summary: Get a receipt image URL
      description: Get a receipt image URL by image ID.
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: user
          in: query
          schema:
            type: string
          description: >-
            The login ID of the user. Optional. The user must have the Web
            Services Admin (Professional) or Can Administer (Standard) user role
            to use this parameter.
          example: <string>
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: <string>
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                ID: <string>
                URI: <string>
    put:
      tags:
        - expense > receiptimages > {id}
      summary: Append a receipt image
      description: >-
        Appends a receipt image to an existing image. The resulting image will
        be a consolidated PDF.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {}
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: user
          in: query
          schema:
            type: string
          description: >-
            The login ID of the user. Optional. The user must have the Web
            Services Admin (Professional) or Can Administer (Standard) user role
            to use this parameter.
          example: <string>
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: <string>
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example: {}
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example: {}
    delete:
      tags:
        - expense > receiptimages > {id}
      summary: Delete a receipt image by ID
      description: Deletes the specified receipt image
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: user
          in: query
          schema:
            type: string
          description: >-
            The login ID of the user. Optional. The user must have the Web
            Services Admin (Professional) or Can Administer (Standard) user role
            to use this parameter.
          example: <string>
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: <string>
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example: {}
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example: {}
  /expense/receiptimages:
    get:
      tags:
        - expense > receiptimages
      summary: Get all receipt IDs by user
      description: >-
        Get a list of all receipt IDs owned by the user associated with the
        access token
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: offset
          in: query
          schema:
            type: string
          description: Starting page offset
          example: <string>
        - name: limit
          in: query
          schema:
            type: string
          description: Number of records to return (default 25)
          example: <integer>
        - name: user
          in: query
          schema:
            type: string
          description: >-
            The login ID of the user. Optional. The user must have the Web
            Services Admin (Professional) or Can Administer (Standard) user role
            to use this parameter.
          example: <string>
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                Items:
                  ID: <string>
                  URI: <string>
                NextPage: <string>
    post:
      tags:
        - expense > receiptimages
      summary: Create a receipt image
      description: Upload a new receipt image.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {}
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: user
          in: query
          schema:
            type: string
          description: >-
            The login ID of the user. Optional. The user must have the Web
            Services Admin (Professional) or Can Administer (Standard) user role
            to use this parameter.
          example: <string>
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                ID: <string>
                URI: <string>
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example: {}
