openapi: 3.0.0
info:
  title: Users
  description: >-
    Provides details of all the client's SAP Concur users that meet the search
    parameters.
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: common
  - name: common > users
paths:
  /common/users:
    get:
      tags:
        - common > users
      summary: Get all users.
      description: Retrieves all users based on the search criteria.
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                Items:
                  Active: <boolean>
                  CellPhoneNumber: <string>
                  EmployeeID: <string>
                  FirstName: <string>
                  ID: <string>
                  LastName: <string>
                  LoginID: <string>
                  MiddleName: <string>
                  OrganizationUnit: <string>
                  PrimaryEmail: <string>
                  URI: <string>
                NextPage: <string>
